import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";

import { cn } from "@/shared/ui/utils";

import "./globals.css";
import { AppProvider } from "@/_providers/app-provider";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Title",
  description: "Generated by bek",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn("bg-background font-sans antialiased", fontSans.variable)}
      >
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
